### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ChromaPIE** [JustDoom/JustNeeded#1]
Crash report: https://www.toptal.com/developers/hastebin/ifukebodid.properties

**Comment by JustDoom** [comment]
Have you tried without any other mods to make sure it's not somehow a mod incompatibility?

**Comment by JustDoom** [comment]
@ChromaPIE 
it has been fixed. Currently waiting on it being approved 
https://www.curseforge.com/minecraft/mc-mods/just-needed/files/3709264
