### ISSUE TITLE
[Bug]: Some items craft doesn't work

### ISSUE THREAD

**Issue by papugt13** [JustDoom/JustNeeded#2]
![1](https://user-images.githubusercontent.com/102837831/161399522-e2066327-4510-4165-b2b9-e4d38b4cd445.jpg)
![3](https://user-images.githubusercontent.com/102837831/161399523-1a2d58b0-5312-4a3d-b1d5-3ede8e77ac28.jpg)
![2](https://user-images.githubusercontent.com/102837831/161399524-b265dedc-5c10-413c-82ba-c92bcc9b1562.jpg)
Mod Version: 1.18.2-1.0.2
Forge Version: 40.0.35
Mods?: only jei

**Comment by JustDoom** [comment]
This works as intended. I am taking this mod in a different direction and some of those recipes seem to take the value out of items like the saddle and nametag

I may create another mod with those recipes and the old recipes
