### ISSUE TITLE
Crash when NPC's interact with Farmland crops.

### ISSUE THREAD

**Issue by HarryPlopper91** [JustDoom/JustNeeded#3]
Multiple server crashes when any NPC interacts with a farmland crop while a player is near that chunk. Issue is only fixed to allow the server to restart by deleting the farmland in that area.

Pastebin link of most recent crash, can provide additional crash logs of other NPCs however they are all mostly the same except for the type of NPC involved.

https://pastebin.com/hF1fvSBH

First few lines of stacktrace leading to believe it is caused by the JustNeeded mod.

Minecraft V1.18.2
```
java.lang.ClassCastException: class net.minecraft.world.entity.monster.ZombieVillager cannot be cast to class net.minecraft.world.entity.player.Player (net.minecraft.world.entity.monster.ZombieVillager and net.minecraft.world.entity.player.Player are in module minecraft@1.18.2 of loader 'TRANSFORMER' @5c448ef)
	at com.imjustdoom.justneeded.listener.CropTrampleListener.cropTrample(CropTrampleListener.java:28) ~[justneeded-1.18.2-1.0.2.jar%23193!/:1.18.2-1.0.2] {re:classloading,pl:eventbus:A}
	at net.minecraftforge.eventbus.ASMEventHandler_76_CropTrampleListener_cropTrample_FarmlandTrampleEvent.invoke(.dynamic) ~[?:?] {}
```

**Comment by JustDoom** [comment]
Thanks for reporting this, I believe I have it fixed and shall release an update within an hour or so. If the update doesnt work you can reply to this issue
