### ISSUE TITLE
Does it support 1.19.4?

### ISSUE THREAD

**Issue by TomerGamerTV** [JustDoom/JustNeeded#5]
Can you add support for 1.19.4? Also..
Could you add images to the gallery inside modrinth?

**Comment by JustDoom** [comment]
I will update it to 1.19.4 in the next couple of days. I will also work on improving the mod page with images and making it look better eventually

**Comment by JustDoom** [comment]
Done!
Forge https://modrinth.com/mod/justneeded/version/1Wp4oGbt
Fabric https://modrinth.com/mod/justneeded/version/lByBgTXt

**Comment by TomerGamerTV** [comment]
> Done!
> 
> Forge https://modrinth.com/mod/justneeded/version/1Wp4oGbt
> 
> Fabric https://modrinth.com/mod/justneeded/version/lByBgTXt

Thx 👌🏻, btw could you add some images too?
